### ISSUE TITLE
regression: PR #143

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura-NIO#154]
Kitura tests fail with the changes related to #143 

We need to do the following:
1. Debug all Kitura failures and fix them
2. Subsequently measure performance and decide if the new changes could be acceptable

I've reverted #143 using #153

**Comment by nethraravindran** [comment]
#143 caused failures in Kitura due to invalid url formed using incorrect components  `_urlComponents?.path = _urlString` 
In this `_urlString` is the uri string from `requestHead` containing both path and percent encoded query. Hence it has to be split and assigned to `path` and `percentEncodedQuery` of the URLComponents respectively.

**Comment by nethraravindran** [comment]
Fix: https://github.com/IBM-Swift/Kitura-NIO/pull/156

**Comment by pushkarnk** [comment]
Merged #156. Thanks @nethraravindran
